### PR TITLE
fix(extended): add demo to show fxHide with used with custom breakpoint

### LINKED ISSUE #961: fxHide with custom breakpoint directive not working in AOT
# Bug Report

#### What is the expected behavior?
Expect for the element to hide at desired custom breakpoint

#### What is the current behavior?
Element hides at desired custom breakpoint when not running aot, but does not hide in aot

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-flex-layout-seed-j5xkix

#### What is the use-case or motivation for changing an existing behavior?
Adding in a min-height breakpoint 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.1.4, Typescript 3.1.6 Flex Layout 7.0.0-beta.22 all browsers

#### Is there anything else we should know?
You'll need to download the stackblitz and run ng serve (angular.json already set to run aot build)

### PR DESCRIPTION
**Pull request by ThomasBurleson**
Add demo showing custom breakpoint working with `fxHide.yba-min-height`

Closes #961.

### CODE REVIEW

**Comment by CaerusKaru** [comment]
@ThomasBurleson Please rebase, and remove commit for `media$` deprecation.

File: src/apps/demo-app/src/app/stack-overflow/hide-custom-bp/hide-with-custom-bp.component.ts [hunk 1]
```diff
@@ -0,0 +1,67 @@
+import {Component, Directive} from '@angular/core';
+import {BREAKPOINT, ShowHideDirective} from '@angular/flex-layout';
+
+const YBA_BREAKPOINT = {
+  alias: 'yba',
+  suffix: 'Yba',
+  mediaQuery: 'screen and (max-height: 800px)',
```
Comment (CaerusKaru) [inline src/apps/demo-app/src/app/stack-overflow/hide-custom-bp/hide-with-custom-bp.component.ts]: Can you change this to 600px? _Some_ people have... smaller displays...

**Comment by ThomasBurleson** [comment]
@CaerusKaru  - final review requested.
