### PR TITLE
fix(ngStyle): should work with preexisting styles

### LINKED ISSUE #936: style attribute is not applied anymore when using ngStyle (version 7.x)
# Bug Report

#### What is the expected behavior?

In the following div the style attribute should work...

```

<div style="background-color: red; height: 100px; width: 100px;" [ngStyle]="this.divStyle">
  First div
</div>


```
#### What is the current behavior?

When I import FlexLayoutModule with @angular/flex-layout - version 7.x the style attribute does not work as expected.. This means it is ignored and only the settings from ngStyle are used.

When I use version 6.x of @angular/flex-layout the style attribute works as expected

#### What are the steps to reproduce?

https://stackblitz.com/edit/angular-cavljx - shows the non working version - updating the angular-flexlayout version to 6 shows the working version

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular 7.1.3, @angular/flex-layout 7.0.0-beta.21

### PR DESCRIPTION
**Pull request by CaerusKaru**
Fixes #936

### CODE REVIEW

File: src/lib/extended/style/style.ts [hunk 1]
```diff
@@ -50,14 +51,13 @@ export class StyleDirective extends BaseDirective2 implements DoCheck {
...
+    const styles = this.nativeElement.getAttribute('style') || '';
+    this.fallbackStyles = this.buildStyleMap(styles);
   }
 
   protected updateWithValue(value: any) {
     const styles = this.buildStyleMap(value);
-    const defaultStyles = this.marshal.getValue(this.nativeElement, this.DIRECTIVE_KEY, '');
-    const fallback = this.buildStyleMap(defaultStyles);
-    this.ngStyleInstance.ngStyle = {...fallback, ...styles};
+    this.ngStyleInstance.ngStyle = {...this.fallbackStyles, ...styles};
```
Comment (ThomasBurleson) [inline src/lib/extended/style/style.ts]: 👍
