### PR TITLE
fix(fxFlex): fxFlex=auto with overlapping breakpoints activated

### LINKED ISSUE #135: Layout with fxFlex="auto" not restoring max-height values properly
**on page load** scans breakpoint overlaps too aggressively [and matches the smallest instead of the largest matching].

```html
<div fxFlex="auto" fxFlex.gt-xs="33%" fxFlex.gt-sm="50%"></div>
```

I'm using fxFlex with 3 breakpoints and IE seems to only pick the first one it passes:

**on page load**, in spite of gt-sm qualifying, it defaults to the gt-xs value. However if I manually re-size the browser it will correct itself. This happens in IE11 only.

### PR DESCRIPTION
**Pull request by ThomasBurleson**
Layout changes from gt-sm will not restore default layout with auto

fix_135

fixes #135.

### CODE REVIEW

**Comment by ThomasBurleson** [comment]
@d3viant0ne - plz review.

File: .gitignore [hunk 1]
```diff
@@ -18,6 +18,8 @@ build/Release
 
 # Users Environment Variables
 .lock-wscript
+yarn.lock
```
Comment (d3viant0ne) [inline .gitignore]: As opposed to ignoring the lock file, I would suggest adding a `.gitattributes` file and then treating it as a binary. Removes the merge conflict issue while still providing the ability to easily see any shifting dependencies upstream.

i.e 

```
# .gitattributes
yarn.lock -diff
* text=auto
bin/* eol=lf
```

File: src/demo-app/app/github-issues/DemosGithubIssues.ts [hunk 2]
```diff
@@ -3,29 +3,34 @@ import {Component} from '@angular/core';
...
-import {FlexLayoutModule}    from "../../../lib";     // `gulp build:components` to deploy to node_modules manually
+import {NgModule}         from '@angular/core';
+import {CommonModule}     from "@angular/common";
+import {MaterialModule}   from "@angular/material";
+import {FlexLayoutModule} from "../../../lib";     // `gulp build:components` to deploy to node_modules manually
 
-import {DemoIssue5345}     from "./issue.5345.demo";
-import {DemoIssue9897}     from "./issue.9897.demo";
-import {DemoIssue181}        from './issue.181.demo';
+import {DemoIssue5345}    from "./issue.5345.demo";
```
Comment (mmalerba) [inline src/demo-app/app/github-issues/DemosGithubIssues.ts]: these first 2 are double imported
