### PR TITLE
fix(flexbox): resolve 'renderer.setStyle()' error

### LINKED ISSUE #270: crash with 2.0.0-beta.8
I got
```
ERROR Error: Uncaught (in promise): TypeError: _this._renderer.setStyle is not a function
TypeError: _this._renderer.setStyle is not a function
    at http://localhost:4200/vendor.bundle.js:15947:29
    at Array.forEach (native)
    at LayoutDirective.BaseFxDirective._applyStyleToElement (http://localhost:4200/vendor.bundle.js:15946:29)
    at LayoutDirective._updateWithDirection (http://localhost:4200/vendor.bundle.js:32683:14)
```
on beta8 but runs smooth on beta7.

After cutting away most of the code, it boils down to this:
\src\app\auth\login\login.component.html
```
  <md-tab label="Password" *ngIf='true'>
      <md-card fxFlex="0 1 18em" fxFlex.xs='100'>
        <md-card-header class="md-primary md-hue-1">
          <b>Local identity (email+password)</b>
        </md-card-header>
        <md-card-content>
          hello world
        </md-card-content>
      </md-card>
  </md-tab>
```
I want to hide a tab (not disable) with 'media$ | async', but the code now crashes with anything in the ngif. Without the ngIf, it won't crash.

however, if I build a new app with just an md-tab and ngif, it won't crash. Some the key is more than mdtab+ngif.

I have just updated everything on 29/4/2017 morning:

- node 790
- npm 450
- angular 410
- angular CLI 101
- angular material 200beta3
- angular flex-layout:
- project does not crash with 2.0.0-beta.7
- project crashes with 2.0.0-beta.8

trimmed source code:
[200b8.zip](https://github.com/angular/flex-layout/files/965941/200b8.zip)

### PR DESCRIPTION
**Pull request by ThomasBurleson**
* Revert back to `Renderer` (from `Renderer2`)
> injecting both Renderers causes intermittent DI issues that manifest errors such as `TypeError: _this._renderer.setStyle is not a function`.
*  Refactor the FxBaseDirective to use a StyleRenderer interface

Fixes #270

### CODE REVIEW

**Comment by ThomasBurleson** [comment]
@crisbeto - please review.

**Comment by ThomasBurleson** [comment]
Fixes https://github.com/angular/flex-layout/issues/270#issuecomment-302836144

screen shot 2017-05-25 at 11 14 17 am

File: src/lib/flexbox/api/base.ts [hunk 1]
```diff
@@ -18,6 +18,13 @@ import {MediaMonitor} from '../../media-query/media-monitor';
 import {MediaQuerySubscriber} from '../../media-query/media-change';
 
 /**
+ * To avoid dependencies on full class Renderer or Renderer,
+ * define interface for the only method used...
+ */
+export interface StyleRenderer {
```
Comment (crisbeto) [inline src/lib/flexbox/api/base.ts]: You can get rid of this one and replace all the usages with the `Renderer`.

**Comment by ThomasBurleson** [comment]
## History

Flex-Layout (beta.8) expects a Renderer2 with function ::setStyle() to injected.
Using M2 (beta.5) with the following setup, a Renderer::setElementStyle() is incorrectly injected.

This appears to be related to the way that M2 handles `<ng-template>`:

Here is a [Plunkr Demo](https://plnkr.co/edit/h8hzyoEyqdCXmTBA7DfK?p=preview)

```html
    <md-tab-group>
      <md-tab>
          <ng-template md-tab-label>
            <span fxShow>tab 1 with fxShow</span>
          </ng-template>
          <md-card fxFlex>
            <md-card-header class="md-primary">
              <b>social identity</b>
            </md-card-header>
            <md-card-content>
              hello world 1
            </md-card-content>
          </md-card>
        </md-tab>
      
        <md-tab label="Password" *ngIf='true'>
          <md-card fxFlex>
            <md-card-header class="md-primary">
              <b>Local identity</b>
            </md-card-header>
            <md-card-content>
              hello world 2
            </md-card-content>
          </md-card>
        </md-tab>
    </md-tab-group>
```

screen shot 2017-05-20 at 1 30 33 pm

> When the `fxShow` used inside the `<ng-template>` is removed, then errors no longer manifest.

File: src/lib/flexbox/api/base.ts (hunk 1 above)
Comment (ThomasBurleson) [inline src/lib/flexbox/api/base.ts]: Since the `BaseFxDirective` directive only uses the method `setElementStyle()` using a StyleRenderer interface clearly declares the intent of the reference.

**Comment by tmburnell** [comment]
Do we have any idea when beta.9 will be cut, so the update will be applied to the NPM version?

**Comment by ThomasBurleson** [comment]
The plan is the end-of next week!
