### PR TITLE
fix(fxLayoutAlign): support flex-start and flex-end options

### LINKED ISSUE #232: FxLayoutAlign="flex-end" renders as flex-start
I'm wrapping my html in a div that looks something like `<div class="flex" fxLayout="column" fxLayoutAlign="flex-end center" fxLayoutGap="10px">` but when I go to inspect element, `justify-content` is set to `flex-start` and not `flex-end`

### PR DESCRIPTION
**Pull request by ThomasBurleson**
Current API translates `start` and `end` to `flex-start` and `flex-end` respectively.
The API should also support the raw `flex-<xxx>` values.

Fixes #232.

### CODE REVIEW

**Comment by ThomasBurleson** [comment]
@mmalerba - please review ?

File: src/lib/flexbox/api/layout-align.ts [hunk 1]
```diff
@@ -157,12 +155,22 @@ export class LayoutAlignDirective extends BaseFxDirective implements OnInit, OnC
...
+      case 'flex-end':
         css['justify-content'] = 'flex-end';
         break;
+      case 'start':
+      case 'flex-start':
+      default :
+        break;
     }
+
+    css['align-items'] = 'stretch';         // default cross axis
```
Comment (mmalerba) [inline src/lib/flexbox/api/layout-align.ts]: nit: why not just put these in the default block? (same above)
