### PR TITLE
fix(api): defer getComputedStyle() calls until ngOnInit phase

### LINKED ISSUE #310: fxShow is setting display:inline; in IE11 and Edge
https://plnkr.co/edit/lF0h5ttXwFiOLrjIgKDr?p=preview

Discovered when using fxShow with md-menu-items. In the above plunkr, the last 4 items in the menu have `fxShow` on them. In IE11 and Edge, `display:inline` is applied to them, which ruins the layout.

### PR DESCRIPTION
**Pull request by ThomasBurleson**
Previously, the Show/Hide directives would query the `display` style during directive instantiation.

For elements instantiated during `*ngFor`, constructor calls to getComputedStyle() will incorrectly return “” due to failures in queries for styles in CSS stylesheets or inline styles. Deferring these types of queries to the ngOnInit() lifecycle event, enables valid response to queries for both inline styles and stylesheets.

Fixes #310.

### CODE REVIEW

**Comment by ThomasBurleson** [comment]
@crisbeto - would you mind reviewing this ?

File: src/lib/flexbox/api/base.ts [hunk 1]
```diff
@@ -92,6 +91,15 @@ export abstract class BaseFxDirective implements OnDestroy, OnChanges {
   // Lifecycle Methods
   // *********************************************
 
+  /**
+   * Use post-component-initialization event to perform extra
+   * querying such as computed Display style
+   */
+  ngOnInit() {
+    this._display = this._getDisplayStyle();
+    this._hasInitialized = true;
```
Comment (crisbeto) [inline src/lib/flexbox/api/base.ts]: `hasInitialized` is only used in a `ngDoCheck` hook. [According to this chart](https://angular.io/guide/lifecycle-hooks), it shouldn't be possible for `ngDoCheck` to fire before `ngOnInit`, making the flag redundant.

File: src/lib/flexbox/api/base.ts [hunk 2]
```diff
@@ -127,7 +135,7 @@ export abstract class BaseFxDirective implements OnDestroy, OnChanges {
     let value = this._lookupStyle(element, 'display');
 
     // Note: 'inline' is the default of all elements, unless UA stylesheet overrides
-    return value ? value.trim() : 'inline';
+    return value ? value.trim() : ((element.nodeType === 1) ? 'block' : 'inline');
```
Comment (crisbeto) [inline src/lib/flexbox/api/base.ts]: Not a huge of nested ternaries. Consider breaking it out into an `if` and a ternary? E.g.

```
if (value) {
  return value;
}

return ((element.nodeType === 1) ? 'block' : 'inline');
```

Comment (crisbeto) [inline src/lib/flexbox/api/base.ts]: I'm not sure that checking that the `nodeType === 1` is a valid way to verify that the element is block-level. 1 only means that it's an `Element` node which is true for almost everything except cases like comments or raw text nodes.

Comment (ThomasBurleson) [inline src/lib/flexbox/api/base.ts]: Hmmm. That is true. Any suggestions? 

Perhaps, we should KISS with ` return value ? value.trim() : 'block'` ?

File: src/lib/flexbox/api/base.ts (hunk 1 above)
Comment (ThomasBurleson) [inline src/lib/flexbox/api/base.ts]: Not sure what you mean. Many of the directives using `ngOnInit()`, the hasInitialized() is a custom method used in the Flex directives.

File: src/lib/flexbox/api/base.ts (hunk 2 above)
Comment (crisbeto) [inline src/lib/flexbox/api/base.ts]: That won't be true necessarily for all cases. One potential solution can be to have a list of the default block-level elements and verify it against the `element.nodeName`, assuming that everything else is `inline`.

Comment (ThomasBurleson) [inline src/lib/flexbox/api/base.ts]: That does not seem reasonable for this library.

File: src/lib/flexbox/api/base.ts (hunk 1 above)
Comment (crisbeto) [inline src/lib/flexbox/api/base.ts]: I mean that the only place I see it being used is https://github.com/angular/flex-layout/pull/374/files#diff-5bc48b81f8309cb16bb22da0a329e466R140 which shouldn't be possible to fire before `ngOnInit`. I might be missing some context here, though.

Comment (ThomasBurleson) [inline src/lib/flexbox/api/base.ts]: Currenty `this.hasInitialized` is only used in `ShowHideDirective::ngOnIniti()`

File: src/lib/flexbox/api/base.ts (hunk 2 above)
Comment (ThomasBurleson) [inline src/lib/flexbox/api/base.ts]: `_lookupStyle()` checks in-line styles or call `getComputedStyle()`. So the expected response usually be defined.  

I think `return value ? value.trim() : 'block'` is a reasonable fallback when `_lookupStyle()` fails.

File: src/lib/flexbox/api/base.ts (hunk 1 above)
Comment (ThomasBurleson) [inline src/lib/flexbox/api/base.ts]: `ngOnChanges()` is called 1x before ngOnInit() and then later when the @Input values are externally changed. The intention of that logic is to SKIP any responses to changes until after `ngOnInit()`.

Comment (crisbeto) [inline src/lib/flexbox/api/base.ts]: Alright, makes sense. I suppose it also depends on the component tree.

File: src/lib/flexbox/api/base.ts (hunk 2 above)
Comment (crisbeto) [inline src/lib/flexbox/api/base.ts]: It will catch most cases, but not the ones that are set to `block` by the UA, which are:

p
h1, h2, h3, h4, h5, h6
ol, ul
pre
address
blockquote
dl
div
fieldset
form
hr
noscript
table

**Comment by ThomasBurleson** [comment]
@crisbeto - working on 1-2 unit tests.

**Comment by ThomasBurleson** [comment]
@crisbeto - unit-tests provided. Can you review last bits?

File: src/lib/utils/style-utils.ts [hunk 3]
```diff
@@ -0,0 +1,91 @@
...
+  return getDom().getStyle(element, styleName);
+}
+
+/**
+ * Determine the inline or inherited CSS style
+ */
+export function lookupStyle(element: HTMLElement, styleName: string, inlineOnly = false): any {
+  let value = '';
+  if (element) {
+    try {
```
Comment (crisbeto) [inline src/lib/utils/style-utils.ts]: AFAIK try/catch has a slight performance overhead. This one could be worked around by checking whether `typeof getComputedStyle !== 'undefined'`.

File: src/lib/utils/style-utils.ts [hunk 4]
```diff
@@ -0,0 +1,91 @@
...
+ * Find the DOM element's inline style value (if any)
+ */
+export function lookupInlineStyle(element: HTMLElement, styleName: string): string {
+  return getDom().getStyle(element, styleName);
+}
+
+/**
+ * Determine the inline or inherited CSS style
+ */
+export function lookupStyle(element: HTMLElement, styleName: string, inlineOnly = false): any {
```
Comment (crisbeto) [inline src/lib/utils/style-utils.ts]: The return value for this one is a string.

File: src/lib/utils/testing/dom-tools.ts [hunk 5]
```diff
@@ -36,8 +36,14 @@ function getStyle(element: any, stylename: string): string {
   return element.style[stylename];
 }
 
-function hasStyle(element: any, styleName: string, styleValue: string = null): boolean {
-  const value = this.getStyle(element, styleName) || '';
+function hasStyle(element: any,
+                  styleName: string,
+                  styleValue: string = null,
+                  inlineOnly = true): boolean {
+  let searchComputed = () => {
```
Comment (crisbeto) [inline src/lib/utils/testing/dom-tools.ts]: Since this is only used once, it seems redundant to define a local function.

File: src/lib/utils/style-utils.ts [hunk 6]
```diff
@@ -0,0 +1,91 @@
+/**
+ * @license
+ * Copyright Google Inc. All Rights Reserved.
+ *
+ * Use of this source code is governed by an MIT-style license that can be
+ * found in the LICENSE file at https://angular.io/license
+ */
+import {Renderer2} from '@angular/core';
+import {ɵgetDOM as getDom} from '@angular/platform-browser';
```
Comment (ThomasBurleson) [inline src/lib/utils/style-utils.ts]: Yes, that is intended. Same as in Angular.

File: src/lib/utils/style-utils.ts (hunk 4 above)
Comment (ThomasBurleson) [inline src/lib/utils/style-utils.ts]: fixed.

File: src/lib/utils/testing/dom-tools.ts (hunk 5 above)
Comment (ThomasBurleson) [inline src/lib/utils/testing/dom-tools.ts]: fixed.

**Comment by ThomasBurleson** [comment]
@crisbeto - Thank you sir for your help and reviews.
