### PR TITLE
fix(fxLayoutGap): mutation observer should run outside the ngZone

### LINKED ISSUE #329: Strange bug: when using fxLayoutGap on container and *ngFor on child
Hi,

I found a strange bug which, I presume, has something to do with fxLayoutGap directive.

My use case was to use a component method to provide items for a *ngFor loop.
I noticed that if the parent of the loop has the directive fxLayoutGap, browser just crash (tested on Chrome and Firefox).
Demo here: https://plnkr.co/edit/paJ7Sb

Hoping you can help me on this.

Thanks in advance.

### PR DESCRIPTION
**Pull request by ThomasBurleson**
Inside the ngZone, the mutation observer and _updateWithValue() style changes causes an infinite recursion. MutationObserver handlers should be executed outside the ngZone.

Fixes #329.

### CODE REVIEW

**Comment by ThomasBurleson** [comment]
@crisbeto - would you mind reviewing these?

File: src/lib/flexbox/api/layout-gap.ts [hunk 1]
```diff
@@ -15,7 +15,7 @@ import {
   Self,
   AfterContentInit,
   Optional,
-  OnDestroy,
+  OnDestroy, NgZone,
```
Comment (crisbeto) [inline src/lib/flexbox/api/layout-gap.ts]: This one should be on the next line.

File: src/lib/flexbox/api/layout-gap.ts [hunk 2]
```diff
@@ -114,22 +115,25 @@ export class LayoutGapDirective extends BaseFxDirective implements AfterContentI
...
    */
   protected _watchContentChanges() {
-    let onMutationCallback = (mutations) => {
-      let validatedChanges = (it: MutationRecord) => {
-        return (it.addedNodes && it.addedNodes.length) ||
-            (it.removedNodes && it.removedNodes.length);
+    this._zone.runOutsideAngular(() => {
+
+      let onMutationCallback = (mutations) => {
+        let validatedChanges = (it: MutationRecord) => {
```
Comment (crisbeto) [inline src/lib/flexbox/api/layout-gap.ts]: Since this is only used once it can be inlined, but I guess that's down to preference. Same goes for the onMutationCallback.

File: src/lib/flexbox/api/layout-gap.ts [hunk 3]
```diff
@@ -114,22 +115,25 @@ export class LayoutGapDirective extends BaseFxDirective implements AfterContentI
...
+          return (it.addedNodes && it.addedNodes.length) ||
+              (it.removedNodes && it.removedNodes.length);
+        };
+
+        // update gap styles only for child 'added' or 'removed' events
+        if (mutations.filter(validatedChanges).length) {
```
Comment (crisbeto) [inline src/lib/flexbox/api/layout-gap.ts]: Instead of using `mutation.filter(...).length`, you can use `mutations.some(...)` which will exit earlier.

File: src/lib/flexbox/api/layout-gap.ts [hunk 4]
```diff
@@ -114,22 +115,25 @@ export class LayoutGapDirective extends BaseFxDirective implements AfterContentI
...
+          this._updateWithValue();
+        }
       };
 
-      // update gap styles only for child 'added' or 'removed' events
-      if (mutations.filter(validatedChanges).length) {
-        this._updateWithValue();
+      if (typeof MutationObserver !== 'undefined') {
+        this._observer = new MutationObserver(onMutationCallback.bind(this));
```
Comment (crisbeto) [inline src/lib/flexbox/api/layout-gap.ts]: The `bind(this)` shouldn't be necessary since it's an arrow function.

File: src/lib/flexbox/api/layout-gap.ts (hunk 2 above)
Comment (crisbeto) [inline src/lib/flexbox/api/layout-gap.ts]: I believe this is a `MutationRecord[]`, not a single `MutationRecord`.

File: src/lib/flexbox/api/layout-gap.ts (hunk 1 above)
Comment (ThomasBurleson) [inline src/lib/flexbox/api/layout-gap.ts]: done.

File: src/lib/flexbox/api/layout-gap.ts (hunk 2 above)
Comment (ThomasBurleson) [inline src/lib/flexbox/api/layout-gap.ts]: fixed.

File: src/lib/flexbox/api/layout-gap.ts (hunk 3 above)
Comment (ThomasBurleson) [inline src/lib/flexbox/api/layout-gap.ts]: done.

File: src/lib/flexbox/api/layout-gap.ts (hunk 2 above)
Comment (ThomasBurleson) [inline src/lib/flexbox/api/layout-gap.ts]: improved.

File: src/lib/flexbox/api/layout-gap.ts (hunk 4 above)
Comment (ThomasBurleson) [inline src/lib/flexbox/api/layout-gap.ts]: removed.

**Comment by ThomasBurleson** [comment]
@crisbeto - nice feedback; as usually. Changes complete.

File: src/lib/flexbox/api/layout-gap.ts [hunk 5]
```diff
@@ -114,22 +116,23 @@ export class LayoutGapDirective extends BaseFxDirective implements AfterContentI
...
-        return (it.addedNodes && it.addedNodes.length) ||
-            (it.removedNodes && it.removedNodes.length);
-      };
-
-      // update gap styles only for child 'added' or 'removed' events
-      if (mutations.filter(validatedChanges).length) {
-        this._updateWithValue();
+    this._zone.runOutsideAngular(() => {
+
+      if (typeof MutationObserver !== 'undefined') {
```
Comment (crisbeto) [inline src/lib/flexbox/api/layout-gap.ts]: Not a big deal, but you can move the `MutationObserver` support check outside of the `runOutsideAngular` to avoid hitting `runOutsideAngular` completely if it's unsupported.

Comment (ThomasBurleson) [inline src/lib/flexbox/api/layout-gap.ts]: true. minor nit. agreed ?

Comment (crisbeto) [inline src/lib/flexbox/api/layout-gap.ts]: Yeah it's pretty minor, no need to change it.
