### PR TITLE
fix(flexbox): scan flex-direction in css stylesheet

### LINKED ISSUE #272: Parent container flexbox injection logic is wrong
When a Flex Layout directive is used on a child element, it expects the parent to work as a FlexBox container. If the parent does not have "display:flex" stylings, then these are injected, inline onto the parent.

If the parent has a classname that defines the FlexBox stylings, these are ignored as only the inline styles are checked. This is wrong.

### PR DESCRIPTION
**Pull request by ThomasBurleson**
`fxFlex` works best if the parent container has flexbox styles assigned (display, flex-direction, etc.). If not assigned (inline or via stylesheet), then these styles are auto-injected inline on the DOM parent element.

When scanning parent DOM element for flexbox flow direction, first scan the in element's inline style and then scan the computed stylesheet for the `flex-direction` value.

> It is assumed that if the parent element has a `flex-direction` style property set, then the other required properties (display, border-box, etc.)  have also been assigned.

Fixes #272, #364.

### CODE REVIEW

**Comment by ThomasBurleson** [comment]
@andrewseguin  - can you review ? Thx.

File: src/lib/flexbox/api/base.ts [hunk 1]
```diff
@@ -146,7 +152,7 @@ export abstract class BaseFxDirective implements OnDestroy, OnChanges {
     try {
       if (element) {
         let immediateValue = getDom().getStyle(element, styleName);
-        value = immediateValue || getDom().getComputedStyle(element).display;
+        value = immediateValue || getDom().getComputedStyle(element)[styleName];
```
Comment (crisbeto) [inline src/lib/flexbox/api/base.ts]: Instead of `getDom().getComputedStyle(element)[styleName]` you can use `getDom().getComputedStyle(element).getPropertyValue(styleName)`.

File: src/lib/flexbox/api/flex.ts [hunk 2]
```diff
@@ -77,10 +77,14 @@ export class FlexDirective extends BaseFxDirective implements OnInit, OnChanges,
...
   @Input('fxFlex.lt-xl') set flexLtXl(val) { this._cacheInput('flexLtXl', val); };
-
   /* tslint:enable */
-  // Explicitly @SkipSelf on LayoutDirective and LayoutWrapDirective because we want the
-  // parent flex container for this flex item.
+
+  /**
+   * Constructor
+   *
+   * Note: Explicitly @SkipSelf on LayoutDirective and LayoutWrapDirective because we are looking
```
Comment (crisbeto) [inline src/lib/flexbox/api/flex.ts]: This note might be better as a regular comment, otherwise it'll show up in any generated docs and typings.

File: src/lib/flexbox/api/flex.spec.ts [hunk 3]
```diff
@@ -118,6 +118,26 @@ describe('flex directive', () => {
       expect(element).not.toHaveCssStyle({'min-width': '30px'});
     });
 
+    it('should CSS stylesheet and not inject flex-direction on parent', () => {
+      componentWithTemplate(`
+        <style type="text/css">
```
Comment (crisbeto) [inline src/lib/flexbox/api/flex.spec.ts]: The `text/css` shouldn't be necessary.

File: src/lib/flexbox/api/base.ts [hunk 4]
```diff
@@ -123,6 +123,12 @@ export abstract class BaseFxDirective implements OnDestroy, OnChanges {
     return value ? value.trim() : ((element.nodeType === 1) ? 'block' : 'inline-block');
```
Comment (crisbeto) [inline src/lib/flexbox/api/base.ts]: Not something that was added in this PR, but instead of hardcoding the `1`, you can use the built-in browser constant: `element.nodeType === Node.ELEMENT_NODE`.

File: src/lib/flexbox/api/base.ts (hunk 1 above)
Comment (ThomasBurleson) [inline src/lib/flexbox/api/base.ts]: IYO, which is preferred/better ?

File: src/lib/flexbox/api/flex.ts (hunk 2 above)
Comment (ThomasBurleson) [inline src/lib/flexbox/api/flex.ts]: Good point. Thx.

File: src/lib/flexbox/api/flex.spec.ts (hunk 3 above)
Comment (ThomasBurleson) [inline src/lib/flexbox/api/flex.spec.ts]: k. will remove.

File: src/lib/flexbox/api/base.ts (hunk 4 above)
Comment (ThomasBurleson) [inline src/lib/flexbox/api/base.ts]: sgtm. Thx.

File: src/lib/flexbox/api/base.ts (hunk 1 above)
Comment (crisbeto) [inline src/lib/flexbox/api/base.ts]: I believe `getPropertyValue` guarantees that the style was recalculated.

Comment (ThomasBurleson) [inline src/lib/flexbox/api/base.ts]: Good to know. Thx.

**Comment by ThomasBurleson** [comment]
@crisbeto using `Node.ELEMENT_NODE` causes problems with angular universal compiles.

**Comment by matheusdavidson** [comment]
Sorry for saying this but i think you guys are trying to apply styles where you don't need to. This is causing many issues and non expected behaviors.

I'm saying this because i had some problems already with things like using ```fxFlex.gt-xs``` and flex layout adding styles even when breakpoint is under ```xs```(talked about this in another issue #296).

@ThomasBurleson, you said: "fxFlex works best if the parent container has flexbox styles assigned.."

I ask you: Wouldn't it be better to let the user choose if he wants a flexbox parent?

Really, i think that worse then having a ```fxFlex``` without flexbox parent(this obvious) is to have no idea why my parent element got flexbox in the first place, since i was already applying it in my css file and flex layout just override the whole thing.

File: src/lib/flexbox/api/base.ts (hunk 1 above)
Comment (Matrosskin) [reply src/lib/flexbox/api/base.ts]: As I know, in iOS 9 the `getPropertyValue` returns `null` instead of empty string as in browsers on other OS. Not sure how much people still use the iOS 9 so my comment is just for info.
