### PR TITLE
fix(ObservableMedia): startup should propagate lastReplay value properly

### LINKED ISSUE #245: Initial value of ObservableMedia not received
If I subscribe to ObservableMedia, the first (initial) value ist not received.
[plunker](https://plnkr.co/edit/EKw5cW92LxPqEZ1oaZtu?p=preview).

The plunker example never receives the first value. In my own app, I get this first value in "xs" and "sm" size. If my browser windows is larger (gt-sm) at the time of loading the app (or refreshing), I do not get the first value.

### PR DESCRIPTION
**Pull request by ThomasBurleson**
ObservableMedia only dispatches notifications for activated, non-overlapping breakpoints.
If the MatchMedia lastReplay value is an *overlapping* breakpoint
(e.g. `lt-md`, `gt-lg`) then that value will be filtered by ObservableMedia
and not be emitted to subscribers.

* MatchMedia breakpoints registration was not correct
  *  overlapping breakpoints were registered in the wrong order
  * non-overlapping breakpoints should be registered last; so the BehaviorSubject's last replay value should be an non-overlapping breakpoint range.
* Optimize stylesheet injection to group `n` mediaQuerys in a single stylesheet
   > screen shot 2017-06-12 at 1 44 43 pm

Fixes #245, #275, #303.

> See working plunker:  https://plnkr.co/edit/yylQr2IdbGy2Yr00srrN?p=preview

### CODE REVIEW

File: src/demo-app/app/shared/media-query-status.ts [hunk 1]
```diff
@@ -31,7 +31,9 @@ export class MediaQueryStatus implements OnDestroy {
   private _watcher : Subscription;
   activeMediaQuery : string;
 
-  constructor(media$ : ObservableMedia) { this.watchMediaQueries(media$); }
+  constructor(media$ : ObservableMedia) {
+    this.watchMediaQueries(media$);
```
Comment (andrewseguin) [inline src/demo-app/app/shared/media-query-status.ts]: What's the `$` for in the variable name? If it's for private but cannot be marked as such for Angular reasons, we use an underscore to preface the variable

File: src/lib/media-query/breakpoints/break-point-registry.ts [hunk 2]
```diff
@@ -30,6 +30,20 @@ export class BreakPointRegistry {
   }
 
   /**
+   * Accessor to sorted list used for
```
Comment (andrewseguin) [inline src/lib/media-query/breakpoints/break-point-registry.ts]: Can combine the two lines into one

File: src/lib/media-query/breakpoints/break-point-registry.ts [hunk 3]
```diff
@@ -30,6 +30,20 @@ export class BreakPointRegistry {
...
+   * registration with matchMedia API
+   *
+   * NOTE: During breakpoint registration, we want to register the overlaps FIRST
+   *       so the non-overlaps will trigger the MatchMedia:BehaviorSubject last!
+   *       And the largest, non-overlap, matching breakpoint should be the lastReplay value
+   */
+  get sortedItems(): BreakPoint[ ] {
```
Comment (andrewseguin) [inline src/lib/media-query/breakpoints/break-point-registry.ts]: Remove space between `[ ]`

File: src/lib/media-query/breakpoints/break-point-registry.ts [hunk 4]
```diff
@@ -30,6 +30,20 @@ export class BreakPointRegistry {
...
+    let overlaps = this._registry.filter(it=>it.overlapping === true);
```
Comment (andrewseguin) [inline src/lib/media-query/breakpoints/break-point-registry.ts]: Add spaces around `=>`

File: src/lib/media-query/match-media.spec.ts [hunk 5]
```diff
@@ -86,13 +86,12 @@ describe('match-media', () => {
...
 
-  it('can observe only a specific custom mediaQuery ranges', () => {
+  it('can observe an array of custom mediaQuery ranges', () => {
     let current: MediaChange, activated;
     let query1 = "screen and (min-width: 610px) and (max-width: 620px)";
     let query2 = "(min-width: 730px) and (max-width: 950px)";
 
-    matchMedia.registerQuery(query1);
-    matchMedia.registerQuery(query2);
+    matchMedia.registerQuery([query1,query2]);
```
Comment (andrewseguin) [inline src/lib/media-query/match-media.spec.ts]: Add space after `,`

File: src/lib/media-query/match-media.ts [hunk 6]
```diff
@@ -76,56 +76,59 @@ export class MatchMedia {
...
-  registerQuery(mediaQuery: string) {
-    if (mediaQuery) {
-      let mql = this._registry.get(mediaQuery);
-      let onMQLEvent = (e: MediaQueryList) => {
-        this._zone.run(() => {
-          let change = new MediaChange(e.matches, mediaQuery);
-          this._source.next(change);
-        });
-      };
+  registerQuery(mediaQuery: string | Array<string>) {
```
Comment (andrewseguin) [inline src/lib/media-query/match-media.ts]: use `string[]`

File: src/demo-app/app/shared/media-query-status.ts (hunk 1 above)
Comment (ThomasBurleson) [inline src/demo-app/app/shared/media-query-status.ts]: this is a community standard to indicate a variable the references an observable. I believe this is used consistently throughout the library.

File: src/lib/media-query/breakpoints/break-point-registry.ts (hunk 2 above)
Comment (ThomasBurleson) [inline src/lib/media-query/breakpoints/break-point-registry.ts]: So I do not mind these comments. It is my hope however that reviewers will focus on content not format.

File: src/lib/media-query/breakpoints/break-point-registry.ts (hunk 4 above)
Comment (ThomasBurleson) [inline src/lib/media-query/breakpoints/break-point-registry.ts]: is this not a lint setting ?

File: src/lib/media-query/match-media.ts (hunk 6 above)
Comment (ThomasBurleson) [inline src/lib/media-query/match-media.ts]: k.

File: src/lib/media-query/match-media.spec.ts (hunk 5 above)
Comment (ThomasBurleson) [inline src/lib/media-query/match-media.spec.ts]: k.

File: src/lib/media-query/breakpoints/break-point-registry.ts (hunk 4 above)
Comment (ThomasBurleson) [inline src/lib/media-query/breakpoints/break-point-registry.ts]: Yes. Will fix with style Linter tool.

File: src/lib/media-query/breakpoints/break-point-registry.ts (hunk 3 above)
Comment (ThomasBurleson) [inline src/lib/media-query/breakpoints/break-point-registry.ts]: k

**Comment by ThomasBurleson** [comment]
Updated. Tx @andrewseguin.

File: src/lib/media-query/breakpoints/break-point-registry.ts (hunk 2 above)
Comment (andrewseguin) [inline src/lib/media-query/breakpoints/break-point-registry.ts]: Tried to give focus to both equally :) My understanding is that we'll want to review this library with the same rigor we give to Material, and we're often strict about even the small things just to maintain quality (even in comments). Apologies if it seems pedantic, just wanting to make sure I'm fair to all PRs

Comment (ThomasBurleson) [inline src/lib/media-query/breakpoints/break-point-registry.ts]: Understood. Thanks for helping review these. Much appreciated.

**Comment by bogacg** [comment]
Please re-check this issue. I think we still have problem when used with `--prod` flag with latest Angular-CLI (1.6)

**Comment by ThomasBurleson** [comment]
@bogacg - Would you mind opening a new issue and perhaps provide a StackBlitz or zip that demonstrates this issue. 
> Note the latest source/nightly builds have been upgraded to Angular  5.1 and RxJS 5.5.
