### PR TITLE
fix(fxFlex): prevent setting min/max-size when grow/shrink is zero

### LINKED ISSUE #153: (fxFlex): zero value for Shrink xor Grow results in overflowing content when basis is px
> I initially posted this on [Stack Overflow](http://stackoverflow.com/questions/41906942/getting-fxflex-px-values-to-behave-like-plain-css-flex-angular2-flex-layout) and then in the Gitter chatroom but have not gotten any responses. So I figured I'd just go ahead and file it here.

Setting px basis value in fxFlex does not behave as expected when either of (but not both) shrink xor grow are set to zero.

[See my plunkr examplifying this.](https://plnkr.co/edit/UtZLRKohE5uimbgez1nt)

Here is an excerpt of the code with some Comments:

```html
    <!-- Box A -->
    <div fxLayout="row" >
       <div fxFlex="0 1 2000px" >  
           <p>... Really Really long Lorem Ipsum ...</p>
           <!-- expecting flex div to shrink to viewport size, 
                with no horizontal scrolling necessary-->
```

```html   
    <!-- Box B -->
    <div fxLayout="column" >
       <div fxFlex="1 0 200px" >  
           <p>... Really Really long Lorem Ipsum ...</p>
           <!-- expecting flex div to grow to accommodate, 
                content size with vertical scrolling if necessary-->
```

In addition, here are screenshots of what I'm getting ("Actual") using only fxFlex API, versus what I should be getting ("Expected") if I used equivalent pure-css flex. 

You can see these interactively at the [plunkr](https://plnkr.co/edit/UtZLRKohE5uimbgez1nt) above. Click on the view to switch between Actual and Expected. 

Note that if your screen's viewport width happens to be greater than `2000px`, then you'll need to make it smaller manually in order to see the effect shown in the screenshot below for "Box A".

actual-flex

expected-css

### PR DESCRIPTION
**Pull request by somombo**
handle various scenarios of grow/shrink being zero:
*  set `min-width`/`min-height` only if `grow != 0`
*  set `max-width`/`max-height` only if `shink != 0`
*  set both min and max if both `grow == 0` AND `shink == 0`
*  add tests for these scenarios
*  remove max-width from  test "should set a min-width when the shrink == 0"

fixes #153

Signed-off-by: Somo <somo@mombo.solutions>

### CODE REVIEW

**Comment by d3viant0ne** [comment]
@somombo - https://travis-ci.org/angular/flex-layout/jobs/199037704

**Comment by somombo** [comment]
@d3viant0ne i'm on it, had forgotten to run the linter

File: src/lib/flexbox/api/flex.ts [hunk 1]
```diff
@@ -301,8 +311,21 @@ export class FlexDirective extends BaseFxDirective implements OnInit, OnChanges,
     let usingCalc = String(basis).indexOf('calc') > -1;
     let isPx = String(basis).indexOf('px') > -1 || usingCalc;
 
-    css[min] = (basis == '0%') ? 0 : isPx ? basis : null;
-    css[max] = (basis == '0%') ? 0 : usingCalc ? null : basis;
```
Comment (ThomasBurleson) [inline src/lib/flexbox/api/flex.ts]: Plz use this:

```js
     // if shrink and grow are both zero then make box inflexible
     //  - should not set a min when the grow is zero
     //  - should not set a max when the shrink is zero
     let isFixed = !grow && !shrink;
     css[min] = (basis == '0%') ? 0 : isFixed || (isPx && grow) ? basis : null;
     css[max] = (basis == '0%') ? 0 : isFixed || (!usingCalc && shrink) ? basis : null;
```

Comment (somombo) [inline src/lib/flexbox/api/flex.ts]: Done.
Though it does look a bit awkward. 

No Problem. 
Thanks for looking over so quick.

Comment (d3viant0ne) [inline src/lib/flexbox/api/flex.ts]: That's honestly a matter of perspective. You can get a log evaluated, very concisely using a ternary and usually on a single line.

Once you get used to scanning it, the `if ( )` conditions start to become a bit tedious to read / write.

Comment (somombo) [inline src/lib/flexbox/api/flex.ts]: Sure, as long we get to a place where #153 and things stemming from it are resolved. I really done care much about the minor details..

Thanks for all the feadback!

**Comment by ThomasBurleson** [comment]
@somombo - just an FYI that you will need to rebase your PR tomorrow after #158  is merged into master. At that point I can finish testing your PR and update to presubmit-for-merge.

**Comment by somombo** [comment]
@ThomasBurleson  - Yeah, no problem! I tested with demos and everthing looked identical to before. 

By the way, none of the demos exemplify usage of something like `1 0 123px` or `0 1 123px`. It may not be a bad idea to provide such examples in future.

**Comment by ThomasBurleson** [comment]
@somombo - want to prepare a cool demo that highlights your changes are useful ?  That would be a great addition to this PR IMO.

**Comment by somombo** [comment]
@ThomasBurleson this is now rebased

**Comment by ThomasBurleson** [comment]
@somombo  - Can you squash plz. Your change list looks huge for some reason.

**Comment by somombo** [comment]
@ThomasBurleson could you post the commit hashes for the extraneous commits just so i know which ones you're referring to?

**Comment by somombo** [comment]
(@googlebot) I had changed my cla email to somo@mombo.solutions

**Comment by ThomasBurleson** [comment]
@somombo - Your change list appears to include this commit  SHA dad69feee8b3efbf43bde007994b9f4425ed4cea that is already in master.

**Comment by somombo** [comment]
@ThomasBurleson Okay I see what you are referring to now.. I'm not sure how to fix that, kindly advise

**Comment by ThomasBurleson** [comment]
try:

```
git co somombo/issue153_maxmin_patch;
git pull --rebase upstream master;
git push -f origin somombo/issue153_maxmin_patch
```

**Comment by somombo** [comment]
@ThomasBurleson  here is what I got for those three commands respectively: 

```
Already on 'somombo/issue153_maxmin_patch'
Current branch somombo/issue153_maxmin_patch is up to date.
Everything up-to-date
```

**Comment by ThomasBurleson** [comment]
@somombo - do this:

* `get rebase -i HEAD~1`, 
* then `d` to remove the commit dad69fee
* then exit and save
* `get push -f origin issue153_maxmin_patch`

**Comment by somombo** [comment]
@ThomasBurleson  thanks looks like that worked. I appreciate it!

**Comment by ThomasBurleson** [comment]
@somombo - I added you as a contributor to this repository. 
> Future PRs should be based on branch from this PR; which allows the core team easier access to your changes.

**Comment by ThomasBurleson** [comment]
@here - CLA was signed.

**Comment by somombo** [comment]
@ThomasBurleson Thanks! I appreciate it.. 

Does that mean for future PRs n patches, I should just work with the master branch on my fork.. rather than creating a `somombo/...`  branch ?

**Comment by somombo** [comment]
@

**Comment by ThomasBurleson** [comment]
@somombo - apologies, but a recent merge to master requires yet another rebase to this PR.

**Comment by somombo** [comment]
@ThomasBurleson is this good?

**Comment by somombo** [comment]
@ThomasBurleson  so what do I do next, do I hit the "squash and merge" or the "rebase and merge" button?

**Comment by ThomasBurleson** [comment]
@somombo  - you should **NEVER** hit the Merge button(s). That is for the Core Team Admins.
I will start the presubmit testing and merge process. THx

**Comment by somombo** [comment]
@ThomasBurleson I figured if there as something I wasn't supposed to do the system would be set up so I wouldn't be able to do it.. but wasn't sure so good thing I asked :)

**Comment by ThomasBurleson** [comment]
@somombo - `master` is protected and accessible only to admins. you have write capabilities so you can create branches and update issues, assign labels, etc.. Just do not merge ;-).
